language: python
python: 
  - "2.7"
env:
  - DJANGO=1.4
  - DJANGO=1.5
install:
  - pip install -r requirements.txt
  - pip install -q Django==$DJANGO --use-mirrors
script:
  - coverage run manage.py test vegancity
  - coverage report --include="vegancity/*"

