language: python
python: 
  - "2.7"
env:
  - DJANGO=1.5
  - DJANGO=1.6
install:
  - pip install coveralls --use-mirrors
  - pip install -q Django==$DJANGO --use-mirrors
before_script:
  - sudo python utils/provision_locally.py travis ansible/site.yml $TRAVIS_BUILD_DIR travis
script:
  - python manage.py test vegancity.PageLoadTest vegancity.FunctionalSearchTest
  - coverage run --source=vegancity manage.py test --exclude-integration-tests
after_success:
  - coveralls
