- name: update apt
  apt: update_cache=yes # TODO: only do this every time on production

- name: install sys apt requirements
  apt: pkg={{ item }} state=latest
  with_items:
    - postgresql
    - postgresql-server-dev-9.1 # TODO use postgresql 9.1
    - postgresql-contrib-9.1
    - python-software-properties
    - python-dev
    - python-pip
    - supervisor # TODO install supervisor manually
    - nginx
    - git
    - unzip

- name: create {{ app_user }} group
  group: name={{ app_user }} state=present system=yes

- name: create {{ app_user }} user
  user: name={{ app_user }} state=present system=yes createhome=no group={{ app_user }}

- name: create log dir
  file: dest={{ log_dir }} owner={{ app_user }} group={{ app_user }} state=directory mode=755

- name: create log files
  copy: src=empty_log.log dest={{ log_dir }}/{{ item }}.log owner={{ app_user }} group={{ app_user }} mode=766
  with_items:
    - gunicorn-access
    - gunicorn-error
    - gunicorn-general
    - vegancity-general
    - vegancity-search
    - django-request
    - django-sql
    - django-general

- name: chown/chmod log files
  file: dest={{ log_dir }}/gunicorn-{{ item }}.log owner={{ app_user }} mode=766
  with_items:
    - gunicorn-access
    - gunicorn-error
    - gunicorn-general
    - vegancity-general
    - vegancity-search
    - django-request
    - django-sql
    - django-general

  with_items:
    - access
    - error
