#################################
# dev env
#################################

- name: clobber settings_local with more dev settings
  template: src=settings_local.py.j2
            dest=/usr/local/vegphilly/vegancity/settings_local.py
            owner=vegphilly
  notify:
    - restart gunicorn

- name: copy dev urls
  copy: src=dev_urls.py dest=/usr/local/vegphilly/vegancity/dev_urls.py owner=vegphilly

- name: install app requirements for dev
  apt: pkg=$item state=latest
  with_items:
    - libtidy-dev
    - firefox
    - xvfb

- name: make postgres user 'vegphilly' a superuser
  sudo: True
  sudo_user: postgres
  postgresql_user: name=vegphilly role_attr_flags=SUPERUSER

- name: install dev pip requirements
  pip: requirements=/usr/local/vegphilly/dev_requirements.txt

- name: write postgres permissions file with more perms
  template: src=pg_hba.conf.j2 dest=/etc/postgresql/9.1/main/pg_hba.conf owner=postgres mode=640
  notify:
    - restart postgres

- name: run syncdb
  sudo: True
  sudo_user: vegphilly
  command: python /usr/local/vegphilly/manage.py syncdb --noinput

- name: run migrate
  sudo: True
  sudo_user: vegphilly
  command: python /usr/local/vegphilly/manage.py migrate --noinput

- name: install dev fixture
  sudo: True
  sudo_user: vegphilly
  command: python /usr/local/vegphilly/manage.py loaddata /usr/local/vegphilly/vegancity/fixtures/public_data.json

#################################
# final checks
#################################

- name: Ensure supervisor is running
  service: name=supervisor state=running

- name: restart gunicorn
  supervisorctl: name=vegphilly_gunicorn state=restarted


