# This playbook will add the additional settings necessary for the various
# debug tools used in development. It also automatically loads a fixture.

- name: clobber settings_local with more dev settings
  template: src=settings_local.py.j2
            dest={{ project_dir }}/vegancity/settings_local.py
            owner={{ app_user }}
  notify:
    - restart gunicorn

- name: install app requirements for dev
  apt: pkg="{{ item }}" state=latest
  with_items:
    - iceweasel
    - xvfb

- name: make postgres user '{{ db_user }}' a superuser
  sudo: True
  sudo_user: postgres
  postgresql_user: name={{ db_user }} role_attr_flags=SUPERUSER

- name: install dev pip requirements
  pip: requirements={{ project_dir }}/dev_requirements.txt

- name: write postgres permissions file with more perms
  template: src=pg_hba.conf.j2 dest=/etc/postgresql/9.3/main/pg_hba.conf owner=postgres mode=640
  notify:
    - restart postgres

- name: install dev fixture
  sudo: True
  sudo_user: "{{ app_user }}"
  command: python {{ project_dir }}/manage.py loaddata {{ project_dir }}/vegancity/fixtures/public_data.json

# this is done in dev because vagrant annoyingly uses a LATIN1 encoding by default
- name: change locale on postgres template
  sudo: True
  sudo_user: postgres
  command: "{{ item }}"
  with_items:
    - psql -c "update pg_database set datistemplate = false where datname = 'template1';"
    - psql -c "drop database template1"
    - psql -c "create database template1 with template=template0 encoding='UTF8' lc_ctype='en_US.UTF-8' lc_collate='en_US.UTF-8';"
    - psql -c "update pg_database set datistemplate = true where datname = 'template1';"

- name: configure detached_dev supervisor job
  template: src=dev_supervisor.conf.j2 dest=/etc/supervisor/conf.d/detached_dev.conf mode=755
  notify:
    - restart supervisor


#################################
# final checks
#################################

- name: Ensure supervisor is running
  service: name=supervisor state=running

- name: restart gunicorn
  supervisorctl: name=vegphilly_gunicorn state=restarted
