- hosts: production_servers
  roles:
    - role: os
    - role: db
    - role: proxy
    - role: fetch_source_code
    - role: app

- hosts: staging_servers
  roles:
    - role: os
    - role: db
    - role: proxy
    - role: fetch_source_code
    - role: app

- hosts: dev_servers
  roles:
    - role: os
    - role: db
    - role: proxy
    - role: app
    - role: dev

